#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

	// Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	int drive;

//main driving code
 while (true)
  {
  		//drive
  	if(vexRT[Btn5U])
  	{
		drive = 1;
	}
	else if(vexRT[Btn5D])
	{
	drive = -1;
	}
	if(drive == 1)
	{
		motor[port4] = vexRT[Ch3];
		motor[port3] = vexRT[Ch3];
		motor[port2] = -vexRT[Ch2];
		motor[port1] = -vexRT[Ch2];
}
else if(drive == -1)
{
		motor[port4] = -vexRT[Ch2];
		motor[port3] = -vexRT[Ch2];
		motor[port2] = vexRT[Ch3];
		motor[port1] = vexRT[Ch3];
}
		//intake
		if(vexRT[Btn5UXmtr2]) // if(vexRT[Btn5UXmrt2])
		{
		motor[port9] = -127;
		motor[port10] = -127;
		}
		else if(vexRT[Btn5DXmtr2])
		{
		motor[port9] = 127;
		motor[port10] = 127;
		}
		else
		{
		motor[port9] = 0;
		motor[port10] = 0;
		}

		//flywheel

		if(vexRT[Btn6UXmtr2])
		{
		motor[port6] = abs(vexRT[Ch2Xmtr2]);
		motor[port5] = abs(vexRT[Ch2Xmtr2]);
	}
	else
	{
		motor[port6] = -abs(vexRT[Ch3Xmtr2]);
		motor[port5] = -abs(vexRT[Ch3Xmtr2]);
	}
		//lift
		if(vexRT[Btn6U])
		{
		motor[port7] = 127;
		motor[port8] = 127;
		}
		else if(vexRT[Btn6D])
		{
		motor[port7] = -127;
		motor[port8] = -127;
		}
		else
			{
			motor[port7] = 0;
			motor[port8] = 0;
		}

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

		}
}
